name: app
description: barcode and delivery applications.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  rxdart: ^0.24.1
  http: ^0.12.1
  google_fonts: ^1.1.0
  beauty_textfield: any
  gestures: ^0.0.1
  barcode_scan: any
  fluttertoast: ^7.0.1
  global_configuration: ^1.5.0
  #flutter_barcode_scanner: ^1.0.1
  shared_preferences: ^0.5.8
  persistent_bottom_nav_bar: any
  double_back_to_close_app: ^1.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/
    - assets/images/
    - assets/cfg/

  uses-material-design: true



