name: app
description: barcode and delivery applications.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.24.1
  get: ^3.5.1
  http: ^0.12.1
  google_fonts: ^1.1.0
  beauty_textfield: any
  gestures: ^0.0.1
  barcode_scan: any
  barcode: ^1.16.1
  flushbar: ^1.10.4
  flutter_custom_dialog: ^1.0.20
  direct_select_flutter: ^1.0.6
  printing: ^3.5.0
  pdf: ^1.10.0
  multilevel_drawer: ^1.0.3
  responsive_grid: ^1.2.0
  flutter_launcher_icons: ^0.7.2
  fluttertoast: ^7.0.1
  qr_code_scanner: ^0.0.13
  #smart_select: ^3.0.3
  awesome_dialog: ^1.1.3
  dropdown_formfield: ^0.1.2
  searchable_dropdown: ^1.1.3
  global_configuration: ^1.5.0
  connectivity: ^0.4.9+2
  provider: ^3.1.0   #for language
  rflutter_alert: ^1.0.3
  sweetalert: ^0.0.1
  dropdown_search: ^0.4.4
  sqflite: any
  splashscreen: ^1.2.0
  path_provider: any
  progress_dialog: ^1.2.4
  dio: ^3.0.1
  #flutter_barcode_scanner: ^1.0.1
  shared_preferences: ^0.5.8
  persistent_bottom_nav_bar: any
  flutter_icons: ^1.0.0+1
  double_back_to_close_app: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate:
  flutter_cupertino_localizations: ^1.0.1 #for language
  cupertino_icons: ^0.1.3
  responsive_screen: ^1.0.0 #responsive use
  responsive_builder: ^0.3.0 #responsive use
  flutter_slidable: ^0.5.7
  camera:
  path: ^1.6.4
  image_picker: ^0.6.7+11
  fxpoi: ^1.0.0
  permission_handler: ^5.0.1+1
  file_picker: ^1.3.6
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  change_app_package_name: ^0.1.2 # to change package name (flutter pub run change_app_package_name:main com.identit_warehouse.identit)


  #provider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
        - asset: assets/fonts/Exo2-Regular.ttf
        - asset: assets/fonts/Exo2-Light.ttf
          style: normal
  assets:
    - assets/
    - assets/images/
    - assets/cfg/
    - assets/fonts/
    - assets/i18n/

  uses-material-design: true

module:
  androidX: true
